-
  name: 'testarea public'
  uriPattern: 'test'
  defaults:
    '@package': 'Marvin.Test'
    '@controller': 'Testarea'
    '@action':     'public'
    '@format': 'html'
-
  name: 'testarea protected'
  uriPattern: 'protected'
  defaults:
    '@package': 'Marvin.Test'
    '@controller': 'Testarea'
    '@action':     'protected'
    '@format': 'html'
